CC = $(CROSS_COMPILE)gcc

TARGET=append2simg
TARGET_EXE=$(TARGET)

SRC = append2simg.c asprintf.c
OBJ = $(SRC:.c=.o)

DEPEND_STATIC_LIB = ./libsparse.a ../../../output/lib/libz.a

CFLAGS = -Wall
CFLAGS += -I../include -I./include -I../../../external/zlib/src

$(TARGET_EXE):$(OBJ) $(DEPEND_STATIC_LIB);$(CC) -o $@ $^
$(filter %.o,$(OBJ)):%.o:%.c;$(CC) $(CFLAGS) -c -o $@ $<

.PHONY:install
install:
	 cp -rf $(TARGET_EXE) ../../../output/bin/

.PHONY:clean
clean:
	 rm -f $(OBJ) $(TARGET_EXE)
