.PHONY:all
all:
	make -f Makefile.libsparse
	make -f Makefile.simg2img
	make -f Makefile.img2simg
	make -f Makefile.append2simg

.PHONY:install
install:
	make -f Makefile.libsparse install
	make -f Makefile.simg2img install
	make -f Makefile.img2simg install
	make -f Makefile.append2simg install
	
.PHONY:clean
clean:
	make -f Makefile.libsparse clean
	make -f Makefile.simg2img clean
	make -f Makefile.img2simg clean
	make -f Makefile.append2simg clean
