.PHONY:all
all:
	make -f Makefile.libext4_utils
	make -f Makefile.make_ext4fs

.PHONY:install
install:
	make -f Makefile.libext4_utils install
	make -f Makefile.make_ext4fs install
	
.PHONY:clean
clean:
	make -f Makefile.libext4_utils clean
	make -f Makefile.make_ext4fs clean
