CC = $(CROSS_COMPILE)gcc

TARGET=mkbootimg

TARGET_EXE=$(TARGET)
OBJ = mkbootimg.o
DEPEND_STATIC_LIB = ../output/lib/libmincrypt.a
CFLAGS = -Werror
CFLAGS += -I../include

$(TARGET_EXE):$(OBJ) $(DEPEND_STATIC_LIB);$(CC) -o $@ $^
$(filter %.o,$(OBJ)):%.o:%.c;$(CC) $(CFLAGS) -c -o $@ $<

.PHONY:install
install:
	 mv $(TARGET_EXE) ../output/bin/

.PHONY:clean
clean:
	 rm -f $(OBJ) $(TARGET_EXE)
