CC = $(CROSS_COMPILE)gcc

TARGET=minigzip

TARGET_EXE=$(TARGET)
OBJ = minigzip.o
DEPEND_STATIC_LIB = ./libz.a
CFLAGS = -Wall
CFLAGS += -I../include -I./src

$(TARGET_EXE):$(OBJ) $(DEPEND_STATIC_LIB);$(CC) -o $@ $^
$(filter %.o,$(OBJ)):%.o:src/test/%.c;$(CC) $(CFLAGS) -c -o $@ $<

.PHONY:install
install:
	 mv $(TARGET_EXE) ../output/bin/

.PHONY:clean
clean:
	 rm -f $(OBJ) $(TARGET_EXE)
