.PHONY:all
all:
	make -f Makefile.mkbootimg
	make -f Makefile.unpackbootimg 

.PHONY:install
install:
	make -f Makefile.mkbootimg install
	make -f Makefile.unpackbootimg install

.PHONY:clean
clean:
	make -f Makefile.mkbootimg clean
	make -f Makefile.unpackbootimg clean
